<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Bad calculator</title>
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css">
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet" />
    <?=$this->section('stylesheets')?>
</head>
<body style="height: 100vh;overflow-y: hidden; display: flex; flex-direction: column; justify-content: center; align-items: center;">
    <div class="app-content">
        <main class="container">
            <?=$this->section('content')?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>Made with s2 by <a href='https://renanliberato.com.br'>Renan Liberato</a></p>
        </div>
    </footer>
    <?=$this->section('javascript')?>
</body>
</html>
