<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div style="display: flex; flex-direction: column;align-items: center; width: 750px;">
    <div style="position: relative;" id='app'>
        <form method="POST">
            <input placeholder='1+1' name="input" value='<?= $input ?>' />
            <button style="width: 100px; margin-right: 0; margin-left: auto;">Calculate</button>
        </form>
        <div id='text-span-container'>
            <?php if ($result): ?>
                <p>I think it is... <?= $result ?>?</p>
            <?php elseif ($sentNoValues): ?>
                <p style="font-size: 13px;">C'mon, input something, I'm not a wizard.</p>
            <?php elseif ($triedToEarly): ?>
                <p style="font-size: 13px;">I'm tired! Wait <?= $triedToEarly ?> seconds.</p>
            <?php else: ?>
                <p>Give me a calculation!</p>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->start('stylesheets') ?>
<style>
    #app {
        width: 840px;
        height: 440px;
        background-image : url(/badcalculator/images/Seller_01_Animation_009.png);
    }

    #text-span-container p {
        margin-bottom: 0;
        text-align: center;
    }
    #text-span-container {
        position: absolute;
        right: 280px;
        top: 135px;
        color: white;
        height: 66px;
        width: 114px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    form {
        display: flex;
        flex-direction: column;
        position: absolute;
        top: 0px;
        left: 120px;
        width: 600px;
        z-index: 999;
        background-color: #2D1712dd;
        padding-top: 20px;
        border-radius: 10px;
        padding: 20px;
    }
</style>
<?php $this->stop() ?>